import React from 'react';
import { useIntl } from 'react-intl';
import Seo, { SITE_URL, toAbsoluteUrl } from '@/components/Seo';
import TransitionLink from '@/components/TransitionLink';

const Arrow = () => <svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 12h13M14 7l5 5-5 5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
const Icon = ({ type }: { type: string }) => {
  const paths: Record<string, React.ReactNode> = {
    thermostat: <><rect x="6" y="3" width="12" height="18" rx="3"/><circle cx="12" cy="11" r="3"/><path d="M9 17h6"/></>,
    wireless: <><path d="M4 9a12 12 0 0 1 16 0M7 12a8 8 0 0 1 10 0M10 15a3 3 0 0 1 4 0"/><circle cx="12" cy="19" r="1" fill="currentColor"/></>,
    zones: <><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 10h18M9 10v10M15 10v10"/></>,
    parts: <><path d="M8 4h8v5H8zM5 15h5v5H5zM14 15h5v5h-5zM12 9v3M7.5 15v-3h9v3"/></>,
    bolt: <path d="M13 2 5 14h6l-1 8 9-13h-6z"/>, water: <path d="M12 2S5.5 10 5.5 15a6.5 6.5 0 0 0 13 0C18.5 10 12 2 12 2Z"/>,
    flame: <path d="M13 2s1 4-2 7c-2-2-3-3-3-3s-4 5-2 10a6.5 6.5 0 0 0 12-1c1-5-5-13-5-13Z"/>, check: <path d="m5 12 4 4L19 6"/>,
  };
  return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{paths[type]}</svg>;
};
const Heading = ({ eyebrow, title, text, light = false }: { eyebrow: string; title: string; text?: string; light?: boolean }) => <div className={`mb-10 max-w-2xl md:mb-14 ${light ? 'text-white' : 'text-[#171815]'}`}><p className={`mb-4 text-[11px] font-bold uppercase tracking-[0.22em] ${light ? 'text-[#f2a45f]' : 'text-[#b45722]'}`}>{eyebrow}</p><h2 className="text-[clamp(2rem,4vw,4rem)] font-medium leading-[1.03] tracking-[-0.045em]">{title}</h2>{text && <p className={`mt-5 max-w-xl text-base leading-7 ${light ? 'text-white/65' : 'text-[#666860]'}`}>{text}</p>}</div>;

const HomePage: React.FC = () => {
  const intl = useIntl();
  const description = intl.formatMessage({ id: 'home.hero.description' });
  const categories = [['thermostat','Smart Thermostats','WiFi · Zigbee · Touch'],['wireless','Wireless Controls','Room-to-boiler control'],['zones','Wiring Centres','Multi-zone management'],['parts','System Components','Sensors · Actuators · Gateways']];
  const products = [['/products/hn-mx860.svg','HN-MX860','Smart touch thermostat'],['/products/hn-ts900.svg','HN-TS900','Premium room controller'],['/products/hn-kn200.svg','HN-KN200','Minimal rotary thermostat']];
  const features = [['01','Application expertise','Product matching across electric, hydronic and boiler systems.'],['02','Flexible engineering','Configurable hardware, interface, protocols and product presentation.'],['03','Quality process','Specification-led development, testing and production checkpoints.'],['04','Responsive support','Clear communication from sampling through repeat production.']];
  return <div className="home-v2 overflow-hidden bg-[#f7f5f0] text-[#171815]">
    <Seo title="Smart Heating Control for Better Living | HeatNexis" description={description} path="/" image="/home-hero-thermostat.jpg" keywords={['smart heating controls','underfloor heating thermostat','OEM thermostat manufacturer']} structuredData={{'@context':'https://schema.org','@type':'Organization',name:'HeatNexis',url:SITE_URL,logo:toAbsoluteUrl('/heatnexis-logo.png')}} />

    <section className="relative min-h-[calc(100svh-73px)] bg-[#e9e4dc]"><img src="/home-hero-thermostat.jpg" alt="Contemporary living room with smart thermostat" className="absolute inset-0 h-full w-full object-cover object-[68%_center]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(18,19,16,.76)_0%,rgba(18,19,16,.48)_38%,rgba(18,19,16,.05)_72%)] max-md:bg-[linear-gradient(180deg,rgba(18,19,16,.18)_0%,rgba(18,19,16,.72)_68%)]"/><div className="relative mx-auto flex min-h-[calc(100svh-73px)] max-w-[1440px] items-end px-5 pb-12 pt-28 md:items-center md:px-10 md:pb-20 lg:px-16"><div className="max-w-[690px] text-white"><p className="mb-6 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[0.23em] text-white/75"><span className="h-px w-8 bg-[#e87b3b]"/>Smart climate, simply connected</p><h1 className="text-[clamp(3.2rem,7.4vw,7.2rem)] font-medium leading-[.89] tracking-[-0.065em]">Comfort,<br/><span className="font-light italic text-[#f3b17c]">in your hands.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-white/75 md:text-lg">Intelligent thermostats and complete heating control systems, engineered for modern homes and global brands.</p><div className="mt-9 flex flex-wrap gap-3"><TransitionLink to="/products" className="inline-flex items-center gap-3 rounded-full bg-[#e76f32] px-6 py-3.5 text-sm font-semibold text-white hover:bg-[#c95621]">Explore products <Arrow/></TransitionLink><TransitionLink to="/contact" className="inline-flex items-center gap-3 rounded-full border border-white/35 bg-white/10 px-6 py-3.5 text-sm font-semibold text-white backdrop-blur-md hover:bg-white hover:text-[#171815]">Talk to our team</TransitionLink></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-20 md:px-10 md:py-28 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><Heading eyebrow="Built as a system" title="One range. Every layer of control."/><p className="max-w-xl pb-14 text-base leading-7 text-[#666860] lg:justify-self-end">From the room interface to the manifold, HeatNexis gives partners a coordinated product family for connected heating projects.</p></div><div className="grid border-l border-t border-[#d9d4ca] sm:grid-cols-2 lg:grid-cols-4">{categories.map(([icon,title,sub],i)=><TransitionLink key={title} to="/products" className="group min-h-[250px] border-b border-r border-[#d9d4ca] p-7 hover:bg-white md:p-8"><div className="flex justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#e8e2d8] text-[#86451f] group-hover:bg-[#e76f32] group-hover:text-white"><Icon type={icon}/></span><span className="text-xs text-[#99998f]">0{i+1}</span></div><h3 className="mt-20 text-xl font-medium tracking-[-.03em]">{title}</h3><p className="mt-2 text-sm text-[#77786f]">{sub}</p></TransitionLink>)}</div></section>

    <section className="bg-[#1b1c19] px-5 py-20 text-white md:px-10 md:py-28 lg:px-16"><div className="mx-auto max-w-[1312px]"><Heading light eyebrow="Heating solutions" title="Designed around the way heat moves." text="Different heat sources need different control logic. Our portfolio connects the right interface, sensor and output for each system."/><div className="grid gap-4 lg:grid-cols-3">{[['bolt','Electric Floor Heating','Precise floor and room sensing for fast-response electric systems.','/page-hero-products-photo.jpg','Direct load · Floor sensor'],['water','Water Floor Heating','Multi-zone comfort with actuators, wiring centres and boiler demand.','/page-hero-about-photo.jpg','Manifold · Multi-zone'],['flame','Gas Boiler Control','Smart room control and reliable wireless boiler switching.','/page-hero-contact-photo.jpg','Wireless · Boiler control']].map(([icon,title,text,image,tag])=><article key={title} className="group relative min-h-[490px] overflow-hidden bg-[#282a26]"><img src={image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-55 transition duration-700 group-hover:scale-[1.03] group-hover:opacity-45"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-black/10"/><div className="relative flex min-h-[490px] flex-col justify-between p-7 md:p-9"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-white/25"><Icon type={icon}/></span><div><p className="mb-4 text-[10px] font-bold uppercase tracking-[.17em] text-[#f3ad77]">{tag}</p><h3 className="text-3xl font-medium tracking-[-.04em]">{title}</h3><p className="mt-4 text-sm leading-6 text-white/65">{text}</p></div></div></article>)}</div></div></section>

    <section className="bg-[#ede9e1] px-5 py-20 md:px-10 md:py-28 lg:px-16"><div className="mx-auto grid max-w-[1312px] items-center gap-16 lg:grid-cols-2"><div className="relative mx-auto h-[610px] w-full max-w-[560px]"><div className="absolute left-0 top-12 h-[470px] w-[72%] overflow-hidden rounded-t-[180px]"><img src="/page-hero-about-photo.jpg" alt="Warm modern home interior" className="h-full w-full object-cover"/></div><div className="absolute bottom-0 right-0 w-[270px] rounded-[36px] border-[8px] border-[#171815] bg-[#171815] p-2 shadow-[0_30px_70px_rgba(25,25,20,.25)]"><div className="overflow-hidden rounded-[25px] bg-[#f7f3ed] p-5"><div className="mx-auto mb-7 h-1 w-14 rounded-full bg-black/15"/><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#8d8d83]">Living room</p><div className="my-8 text-center"><span className="text-6xl font-light tracking-[-.07em]">22.5°</span><p className="mt-2 text-xs text-[#85857d]">Heating to 23°</p></div><div className="relative mx-auto my-7 h-40 w-40 rounded-full border-[13px] border-[#e6ded1]"><div className="absolute inset-[-13px] rotate-45 rounded-full border-[13px] border-transparent border-r-[#e76f32] border-t-[#e76f32]"/></div><div className="grid grid-cols-3 gap-2 text-center text-[9px] text-[#77786f]"><span>Schedule</span><span>Home</span><span>Energy</span></div></div></div></div><div><Heading eyebrow="Smart app control" title="Your home, at the right temperature before you arrive." text="Adjust rooms, build schedules and follow energy use from one clear mobile experience—at home or away."/><div className="grid gap-5 sm:grid-cols-2">{[['wireless','Control anywhere'],['zones','Room-by-room schedules'],['check','Clear system status'],['bolt','Energy-aware routines']].map(([icon,label])=><div key={label} className="flex items-center gap-3 border-t border-[#cfc9be] pt-4 text-sm font-semibold"><span className="text-[#b45722]"><Icon type={icon}/></span>{label}</div>)}</div></div></div></section>

    <section className="bg-white px-5 py-20 md:px-10 md:py-28 lg:px-16"><div className="mx-auto max-w-[1312px]"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><Heading eyebrow="Featured products" title="Controls made to be lived with."/><TransitionLink to="/products" className="mb-14 inline-flex items-center gap-2 text-sm font-bold text-[#93451e]">View all products <Arrow/></TransitionLink></div><div className="grid gap-5 md:grid-cols-3">{products.map(([image,name,type])=><TransitionLink to="/products" key={name} className="group bg-[#f3f1ec] p-6 md:p-8"><div className="flex aspect-square items-center justify-center"><img src={image} alt={`${name} ${type}`} className="h-[76%] w-[76%] object-contain transition duration-500 group-hover:-translate-y-2"/></div><div className="flex items-end justify-between border-t border-[#d8d4cc] pt-5"><div><h3 className="text-xl font-medium">{name}</h3><p className="mt-1 text-sm text-[#77786f]">{type}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#ccc6bb] group-hover:bg-[#171815] group-hover:text-white"><Arrow/></span></div></TransitionLink>)}</div></div></section>

    <section className="grid lg:grid-cols-2"><div className="min-h-[520px] bg-[url('/page-hero-products-photo.jpg')] bg-cover bg-center"/><div className="flex items-center bg-[#bb5a28] px-6 py-20 text-white md:px-14 lg:px-20"><div className="max-w-xl"><p className="mb-5 text-[11px] font-bold uppercase tracking-[.22em] text-white/65">OEM / ODM partnership</p><h2 className="text-[clamp(2.5rem,5vw,5.5rem)] font-medium leading-[.98] tracking-[-.055em]">Your brand.<br/>Our heating expertise.</h2><p className="mt-7 leading-7 text-white/75">From panel finish and firmware to packaging and documentation, develop a thermostat range shaped for your market.</p><div className="mt-9 grid grid-cols-2 gap-x-8 gap-y-4 text-sm">{['Industrial design','Firmware options','Private-label packaging','Project documentation'].map(x=><span key={x} className="flex items-center gap-2 border-t border-white/25 pt-3"><Icon type="check"/>{x}</span>)}</div><TransitionLink to="/contact" className="mt-9 inline-flex items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-[#8e3d18]">Start your project <Arrow/></TransitionLink></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-20 md:px-10 md:py-28 lg:px-16"><div className="grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><Heading eyebrow="Why HeatNexis" title="Confidence, from specification to delivery." text="A practical partner for product selection, customization and long-term heating-control programs."/><div className="grid sm:grid-cols-2">{features.map(([n,t,d])=><div key={n} className="border-l border-t border-[#d7d2c8] p-6 sm:p-8"><span className="text-xs text-[#aa5b2f]">{n}</span><h3 className="mt-12 text-xl font-medium">{t}</h3><p className="mt-3 text-sm leading-6 text-[#72736b]">{d}</p></div>)}</div></div></section>

    <section className="border-y border-[#d7d2c8] bg-[#efebe4] px-5 py-16 md:px-10"><div className="mx-auto grid max-w-[1312px] gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.22em] text-[#a34e23]">Certifications</p><h2 className="mt-4 text-3xl font-medium tracking-[-.04em]">Documentation for the markets you serve.</h2></div><div className="grid grid-cols-2 gap-px overflow-hidden border border-[#d6d0c5] bg-[#d6d0c5] sm:grid-cols-4">{['CE','RoHS','RED','REACH'].map(x=><div key={x} className="flex h-24 items-center justify-center bg-[#f7f5f0] text-lg font-semibold tracking-[.08em] text-[#55564f]">{x}</div>)}</div></div></section>
    <section className="bg-white px-5 py-20 md:px-10 lg:px-16"><div className="mx-auto max-w-[1312px]"><p className="text-center text-[11px] font-bold uppercase tracking-[.22em] text-[#8b8d84]">Global partners · Key markets served</p><div className="mt-10 grid grid-cols-2 gap-4 text-center text-xl font-medium text-[#696a63] md:grid-cols-4">{['Europe','North America','Middle East','Asia Pacific'].map(x=><div key={x} className="border-y border-[#e2ded6] py-7">{x}</div>)}</div></div></section>
    <section className="bg-[#181916] px-5 py-20 text-white md:px-10 md:py-28 lg:px-16"><div className="mx-auto flex max-w-[1312px] flex-col items-start justify-between gap-10 lg:flex-row lg:items-end"><div><p className="mb-5 text-[11px] font-bold uppercase tracking-[.22em] text-[#e78a50]">Start a conversation</p><h2 className="max-w-4xl text-[clamp(2.7rem,6vw,6.5rem)] font-medium leading-[.94] tracking-[-.06em]">Let’s build better comfort, together.</h2></div><TransitionLink to="/contact" className="inline-flex shrink-0 items-center gap-4 rounded-full bg-[#e76f32] px-7 py-4 text-sm font-bold hover:bg-[#f27e40]">Get a quote <Arrow/></TransitionLink></div></section>
  </div>;
};
export default HomePage;
